### ISSUE TITLE
機能実装：イベント参加人数が0人の時になった際のイベント削除機能実装 4H

### ISSUE THREAD

**Issue by kkkkoki** [camp-team/team-mukaida#107]
イベントに参加しているユーザーが0人になった時（最後のユーザーが退会処理、イベント抜ける行動）イベントを削除する機能実装。

functionでimageなどもバッジ処理で削除

**Comment by mukaida-r** [comment]
オーナー譲渡機能(最後のオーナーがイベントを削除する。)があるので、イベント参加者が0になるタイミングがない
